### ISSUE TITLE
Tests failing: Looks like there is no 32 bit version of MySQL workbench anymore

### ISSUE THREAD

**Issue by guiweber** [just-install/registry#10]
Download page : https://dev.mysql.com/downloads/workbench/

The new version is 64 bits only. Should we keep a separate 32 bit version in the registry?

@lvillani it could be a good idea to consider having 64 bit only entries as some projects will abandon 32 bit builds sooner or later...

**Comment by lvillani** [comment]
@guiweber I think we can use the 64bit version for now and add a separate, older, 32-bit entry only if users expressively request it.

**Comment by guiweber** [comment]
The issue I see is that if we put the 64 version as the x86 entry, someone with a 32bit system will be able to download it through just-install and may not understand why it doesn't work. It would be better to allow us to have registry entries with a 64bit version only. That way, if someone tries to install it on a 32 bit system, just-install can provide an error message telling them that there is not 32 bit version available.

**Comment by lvillani** [comment]
I forgot that just-install fails if it cannot find the x86 entry. I opened https://github.com/just-install/just-install/issues/235 to track this issue.

**Comment by geek1011** [comment]
Tests aren't failing anymore. Let's close this in favour of just-install/just-install#235.
