### ISSUE TITLE
oldfoss links broken

### ISSUE THREAD

**Issue by geek1011** [just-install/registry#106]
````
2018/10/22 20:33:25 Get http://app.oldfoss.com:81/download/Audacity/audacity-win-2.3.0.exe: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018/10/22 20:33:25 Get http://app.oldfoss.com:81/download/Classic-Shell/ClassicShellSetup_4_3_1.exe: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018/10/22 20:33:25 Get http://app.oldfoss.com:81/download/qBittorrent/qbittorrent_4.1.3_setup.exe: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018/10/22 20:33:25 Get http://app.oldfoss.com:81/download/qBittorrent/qbittorrent_4.1.3_x64_setup.exe: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
````

**Comment by cyagon** [comment]
@geek1011 we could change the download links.
classicshell has an official mirror at mediafire, qbittorrent has one at sourceforge, but audacity has [explicitly none](https://forum.audacityteam.org/viewtopic.php?t=94040) aside from third partys like majorgeeks or filehorse.....

**Comment by lvillani** [comment]
I'm removing Audacity since there are no officially supported download mirrors. I'll work on the others as soon as I have a bit of free time (feel free to tackle them in the meantime, though).

**Comment by lvillani** [comment]
This should be fixed now that we download ClassicShell and qBittorrent from SF mirrors.
