### ISSUE TITLE
update json schema

### ISSUE THREAD

**Issue by cyagon** [just-install/registry#108]
in order for the AppVeyor CI builds to run correctly (at least sort of), i removed the "x86" property from the jsonschema: https://github.com/just-install/registry/commit/6c775e4849aa9d5173707be42309798fad99f44f
it needs to be updated so it can check if at least one of the "x86" or "x86_64" properties are set.

**Comment by geek1011** [comment]
Done

**Comment by cyagon** [comment]
Thanks :)
