### ISSUE TITLE
piriform software silently installing chrome

### ISSUE THREAD

**Issue by cyagon** [just-install/registry#109]
Installers for piriform software (ccleaner, defraggler, recuva) are silently installing chrome when installed over just-install:
https://wpkg.org/Defraggler
for ccleaner, there is a "slim-installer" which doesnt do that, but for the others there is currently no other way than manually placing keys into the windows registry.

Should the just-install entries for defraggler and recuva getting removed?

**Comment by lvillani** [comment]
That's bad. I think we should remove all software by Piriform that silently installs Chrome (the same should be done for any other package that we are aware of).

I have created a ticket to add a mechanism that allows us to keep these entries in the registry but show an hard error if someone tries to install them. The idea here is to call out companies that have such user-hostile behavior.

I have also created a ticket to detail an "eligibility criteria" for new and existing entries.

**Comment by lvillani** [comment]
Should be fixed now, closing.
