### ISSUE TITLE
Pycharm-community install fails

### ISSUE THREAD

**Issue by guiweber** [just-install/registry#115]
![capture](https://user-images.githubusercontent.com/7825368/51213057-0f51a900-18e8-11e9-9337-521d56506b66.PNG)

**Comment by mimi89999** [comment]
I have the same issue

**Comment by lvillani** [comment]
I changed PyCharm’s entry to run the installer as-is, which means it requires user interaction. This the best we can do until JetBrains fixes its own installer.
