### ISSUE TITLE
Add Speccy and Defraggler to the catalog

### ISSUE THREAD

**Issue by aaronfranke** [just-install/registry#118]
It makes sense to add these, since you already have CCleaner on the list.

**Comment by lvillani** [comment]
All Piriform products besides CCleaner silently install Google Chrome. Apparently there isn't a way to disable this behaviour. Since this is considered user-hostile, they have been removed. CCleaner ships a second installer that doesn't do this, that's what we have in our registry.

**Comment by aaronfranke** [comment]
Why not hide them until Google Chrome is selected, then?
