### ISSUE TITLE
AppVeyor CI builds failing

### ISSUE THREAD

**Issue by tlm-2501** [just-install/registry#124]
It seems to be unable to find https://unstable.just-install.it (and, indeed, that link is broken). AppVeyor needs to be pointed to this new website and documentation for manual testing updated accordingly (in README.md)

**Comment by geek1011** [comment]
Good catch! @lvillani?

**Comment by geek1011** [comment]
Now we need to deal with the fosshub and oldfoss failures.

**Comment by lvillani** [comment]
I'm closing this one since the root issue should be fixed. There's #106 for fosshub and oldfoss failures.
