### ISSUE TITLE
wrong links for doublecmd and qbittorrent

### ISSUE THREAD

**Issue by freddii** [just-install/registry#141]
For doublecmd:
the working links  are simply the same links just with https instead of http

For qbittorrent:
"x86": "https://netcologne.dl.sourceforge.net/project/qbittorrent/qbittorrent-win32/qbittorrent-4.1.6/qbittorrent_4.1.6_setup.exe",
"x86_64": "https://netix.dl.sourceforge.net/project/qbittorrent/qbittorrent-win32/qbittorrent-4.1.6/qbittorrent_4.1.6_x64_setup.exe"

**Comment by lvillani** [comment]
This appears to be OK in master. Closing.
