### ISSUE TITLE
add copyq darktable diffuse flightgear glasswire godot kontalk makehuman qmmp sonic-pi sqlitebrowser supertuxkart texmaker

### ISSUE THREAD

**Issue by freddii** [just-install/registry#143]
websites:
copyq: https://sourceforge.net/projects/copyq/files/latest/download
darktable: https://github.com/darktable-org/darktable/releases/download/release-2.6.2/darktable-2.6.2-win64.exe
diffuse: http://diffuse.sourceforge.net/download.html
flightgear: https://sourceforge.net/projects/flightgear/files/release-2018.3/FlightGear-2018.3.2.exe/download
glasswire: https://download.glasswire.com/GlassWireSetup.exe
godot: https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_win64.exe.zip
kontalk: https://github.com/kontalk/desktopclient-java/releases/download/v3.1.2/KontalkInstaller-3.1.2.exe
makehuman: http://download.tuxfamily.org/makehuman/releases/1.1.1/makehuman-1.1.1-win32.zip
qmmp: http://qmmp.ylsoftware.com/files/windows/1.3/qmmp-1.3.2-win32.exe
sonic-pi: https://sonic-pi.net/files/releases/v3.1.0/Sonic-Pi-for-Win-v3.1.0.msi
sqlitebrowser: http://sqlitebrowser.org/dl/
supertuxkart: https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.0/SuperTuxKart%201.0%20installer-64bit.exe/download
texmaker: http://www.xm1math.net/texmaker/assets/files/Texmaker_5.0.3_Win_x64.msi

**Comment by lvillani** [comment]
I'm sorry, we don't have a procedure to request new packages and it's unlikely that one of the maintainers will add a software that he or she does not actively use to the registry. Your best bet is to try and submit the necessary changes to the registry yourself.

From this list I think we are likely to accept only darktable, glasswire, sqlitebrowser and texmaker.

I'm closing this issue. I'm available to review any pull request made to add the aforementioned entries to the registry.
