### ISSUE TITLE
not able to install bleachbit, doublecmd, qbittorrent and wireshark with just-install on Windows 10

### ISSUE THREAD

**Issue by freddii** [just-install/registry#146]
not working:

just-install bleachbit
just-install doublecmd
just-install qbittorrent
just-install wireshark

**Comment by lvillani** [comment]
Wireshark and qBittorrent _should_ be fixed. Still need to work on doublecmd and bleachbit.

**Comment by mimi89999** [comment]
I fixed `bleachbit` in https://github.com/just-install/registry/commit/29dbd6d90806066bf7be59b0746795bc6cb6ca57
