### ISSUE TITLE
Jetbrains Toolbox did not install

### ISSUE THREAD

**Issue by ideaman924** [just-install/registry#150]
Is this a bug? I tried `just-install jetbrains-toolbox`. After selecting yes to the UAC prompt the install never happened and the prompt returned:

```
C:\Users\ideaman924>just-install jetbrains-toolbox

C:\Users\ideaman924>
```

What's going on?

**Comment by lvillani** [comment]
On my test system I get an error, instead of a silent failure. The error should be fixed. Please try forcing a new download.

**Comment by ideaman924** [comment]
I can't reproduce this error as I've manually installed Toolbox. If it's fixed it's OK to close the issue. Can anybody else test
