### ISSUE TITLE
Unable to update the registry

### ISSUE THREAD

**Issue by user2301** [just-install/registry#151]
Following this documentation https://github.com/just-install/registry/blob/master/README.md,
I tried to test the changes locally. I get the following error. I am not able to update the registry.
I have corporate proxy configured on my system.
`version used: just-install version 3.4.5`

![image](https://user-images.githubusercontent.com/16040919/58940680-67475a00-877a-11e9-9931-34e87e76da6d.png)

**Comment by geek1011** [comment]
Can you access it in a web browser?

**Comment by user2301** [comment]
Yes I can access it in a web browser

**Comment by user2301** [comment]
Is it possible to host registry in our internal server? (to support the
following below packages/tools other than standard packages)

Internal or custom tools installation e.g. tool_setup.exe
Third party tools such as Matlab, source tree.
Internal software binaries (*.dll, *.elf, etc.)

**Comment by user2301** [comment]
Is it possible to host registry in our internal server? (to support the following below packages/tools other than standard packages)

Internal or custom tools installation e.g. tool_setup.exe
Third party tools such as Matlab, source tree.
Internal software binaries (*.dll, *.elf, etc.)

**Comment by geek1011** [comment]
Yes. All you need to do is host the just-install.json file and any private installers.

**Comment by user2301** [comment]
Okay thank you. So we need to create our own installer? Is it not possible to refer the json file from our hosted private gitlab repository  as below 
 just-install -remoteURL  "https://example.com/repository/registry/.."

**Comment by geek1011** [comment]
You can use the --registry flag to set the URL to the registry. What do you mean by creating your own installer?

**Comment by user2301** [comment]
I have a package with couple of steps for execution like setting environment  variables, creating start menu shortcut, calling vcredist_x64.exe and other execution steps in order to install the package. This package is (setup.exe) contained in zip file. In order to specify this package in the json file, I have to specify "kind:custom" and create own installer package like nsis which is mentioned in json file.
( https://github.com/just-install/registry/blob/master/docs/registry.md)

**Comment by user2301** [comment]
Hi,
I tried using --registry flag to set the URL to registry file. But, I get error as no such file found. The just-install.json file is in private gitlab repository.
 `just-install --registry https://private_token:etjrtnrghgvnuh@mygitlab.test.com/api/v4/projects/111/repository/files/just-install.json/raw?ref=master`

**Comment by geek1011** [comment]
OK, I just had a closer look at the code, and it appears that it doesn't support loading from a URL at the moment. I'll probably implement this when I have time. For now, loading from a network share or building a binary with the URL changed are possible workarounds.

**Comment by user2301** [comment]
Okay thank you so much. How can I build a binary with the URL changed? what are the requirements to build? Is there any documentation on that? Please kindly share.

**Comment by geek1011** [comment]
You need Go, git, and Wix installed, then you just clone the repository and run `go run make.go`. The registry URL is at the top of `pkg/justinstall/registry.go`.

**Comment by user2301** [comment]
Hi, I installed Go, git and Wix. Downloaded the repository from master branch and updated the URL in the registry.go and then executed the below command on Windows 10. I got the below error. Do i need to set any path?

> Go 1.12.6
> Git 2.20.1
> Wix Toolset v3.11.1

```
C:\Users\Documents\just-install\just-install-master>go run make.go
2019/06/19 11:00:02 deleting just-install
2019/06/19 11:00:02 deleting just-install.exe
2019/06/19 11:00:02 building version unstable
2019/06/19 11:00:10 building MSI installer
2019/06/19 11:00:10 cannot build MSI installer: exec: "candle": executable file not found in %PATH%
exit status 1
```

**Comment by geek1011** [comment]
Yep.

**Comment by user2301** [comment]
Hi..
The Go path is already set. C:\Go\bin.
which other executable file path do i need to add %PATH%?

**Comment by geek1011** [comment]
The path to WiX.

**Comment by lvillani** [comment]
The `fetch` branch actually supports URLs for the `-r` command line switch. It's a bit hackish at the moment. It's the branch in which I am (slowly) rewriting the HTTP client.

**Comment by user2301** [comment]
> The path to WiX.
Thanks. Now it not showing error.

**Comment by user2301** [comment]
> The `fetch` branch actually supports URLs for the `-r` command line switch. It's a bit hackish at the moment. It's the branch in which I am (slowly) rewriting the HTTP client.

Thanks a lot. Looking forward to use '-r' command line switch.

**Comment by user2301** [comment]
Hi,
Is it also possible to add the username(-u) and API token or password (-p) along with the registry URL (-r) in command line to pass these credentials to the registry file for packages to download?
`just-install -u "jon" -p "494uttjj" -r  https://repository/files/just-install.json`

**Comment by user2301** [comment]
> The `fetch` branch actually supports URLs for the `-r` command line switch. It's a bit hackish at the moment. It's the branch in which I am (slowly) rewriting the HTTP client.

Hi,
Any tentative date that these changes might be available on master branch?

**Comment by geek1011** [comment]
Hi, I'm not sure when @lvillani will finish working on those changes, but at the moment, I currently use Linux for the majority of the time (and I'm taking a short break from OSS stuff in general right now). When I have more need of Windows for testing stuff, I'll probably see if I can work on some of this. I'd say the earliest you would see this implemented is late August.

**Comment by user2301** [comment]
> Hi, I'm not sure when @lvillani will finish working on those changes, but at the moment, I currently use Linux for the majority of the time (and I'm taking a short break from OSS stuff in general right now). When I have more need of Windows for testing stuff, I'll probably see if I can work on some of this. I'd say the earliest you would see this implemented is late August.

Okay thank you very much!

**Comment by lvillani** [comment]
Hi @user2301! I don't expect to be able to finish my work on said branch before the end of the year. Some other things got in the way and I have to focus on those, for the time being.

**Comment by lvillani** [comment]
The `--registry` switch has been available in the `master` branch (and unstable builds that can be downloaded from CI) for a while. Also, a new release is imminent. I'm closing this issue for now.
