### ISSUE TITLE
Placeholder for credentials to download URL in registry file

### ISSUE THREAD

**Issue by user2301** [just-install/registry#153]
Hi, 
I have the following sample registry file. To download the package from artifactory server, I need to pass username and artifactory API token to the download url. Is is possible to have placeholder for username and API token in the URL in the same way like placeholders https://github.com/just-install/registry/blob/master/docs/registry.md#placeholders for {{.version}} and where can we add it? Or is it possible to pass these values from just-install command line options? 
```
{
  "$schema": "./just-install-schema.json",
  "version": 4,
  "packages":{
   "toolA":{
	"installer":{
	 "kind": "nsis",
		"x86_64": "https://username:API_token_here@test.artifactory.com/artifactory/tools/test/toolA.exe"
      }
	}
	}
	}
```

**Comment by lvillani** [comment]
I’m afraid we currently have no plans to implement this feature.
