### ISSUE TITLE
JDK (x86) broken

### ISSUE THREAD

**Issue by geek1011** [just-install/registry#18]
`link_reachability_test.go:96: jdk (x86): http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-windows-i586.exe, Status code: expected 200, got 404`

**Comment by guiweber** [comment]
@lvillani Not sure how the download worked without accepting the license agreement before, but here is a solution that probably still works: https://gist.github.com/gsitgithub/c7010ea8945a7b1b9f754345f2dd5cd3

This issue would then be linked to https://github.com/just-install/just-install/issues/231

**Comment by lvillani** [comment]
> @lvillani Not sure how the download worked without accepting the license agreement before

There's an ugly hack [here](https://github.com/just-install/just-install/blob/648c5d2d7b6dabc35afa142aa3d559318827b2ba/util.go#L192-L195), we probably need to change the cookie's name.

*Le sigh*

**Comment by Schokobecher** [comment]
Is this still a problem? the cookie name and value seem to be the same.

**Comment by guiweber** [comment]
I created an updater entry which captures the hash, and it looks like it's working now.
