### ISSUE TITLE
eclipse-java doesn't have a link in StartMenu

### ISSUE THREAD

**Issue by mimi89999** [just-install/registry#181]
After installing `eclipse-java` I noticed that it doesn't have a link in the start menu. All other apps that I installed had it. I think that to stay consistent `eclipse-java`  should also create a link in the start menu.

**Comment by geek1011** [comment]
Just-install doesn't control what the installers do; all it does is run them silently. I think this is out of the scope of j-i. @lvillani?

**Comment by mimi89999** [comment]
> Just-install doesn't control what the installers do

@geek1011 That's true, but in this case the installer is `zip`, so _just-install_ just extracts the archive. It would be nice if it also created links. I opened an issue for this https://github.com/just-install/just-install/issues/310

**Comment by lvillani** [comment]
We risk going down the rabbit hole if we start doing the job of traditional installers. I believe users wishing Start Menu entries should push upstream to provide a proper installer.

**Comment by mimi89999** [comment]
Well, it's usually difficult to get upstream to change their installer. I don't think that creating shortcuts would add much work. It's like 5 lines of code. Why would this be an issue?
