### ISSUE TITLE
FreeFileSync broken

### ISSUE THREAD

**Issue by geek1011** [just-install/registry#19]
`link_reachability_test.go:96: freefilesync (x86): http://www.freefilesync.org/download/FreeFileSync_9.0_Windows_Setup.exe, Status code: expected 200, got 404`

**Comment by guiweber** [comment]
FreeFileSync was auto-updated to 9.1 in https://github.com/just-install/registry/commit/176384dede4e965489b02ae2e1246b98c8c293cb yesterday evening and seems to work fine
