### ISSUE TITLE
Add style validation in CI

### ISSUE THREAD

**Issue by mimi89999** [just-install/registry#205]
I noticed that the updater in https://github.com/just-install/registry/commit/9f2ebfce92e34c4455e60c358fbed08a874147fe rewrote the `sumatrapdf` entry added in the previous commit https://github.com/just-install/registry/commit/a8ab40296d8747b6fcd68530f1d0d664f68e9437. Maybe style validation of the registry should be added to CI?

**Comment by geek1011** [comment]
That was just a side effect of the updater. IMO, there's not much point duplicating the re-formatting in CI.

**Comment by lvillani** [comment]
The new entry, however, has 4-space indentation whereas the rest of the file has 2-space indent. The updater should output a file with consistent spacing, finer details can be fixed manually by running `prettier` once in a while.
