### ISSUE TITLE
Plex broken - no 32 bit version available

### ISSUE THREAD

**Issue by geek1011** [just-install/registry#21]
`link_reachability_test.go:96: plex-home-theater (x86): https://downloads.plex.tv/plex-home-theater/1.4.1.469-47a90f01/PlexHomeTheater-1.4.1.469-47a90f01-windows-x86.exe, Status code: expected 200, got 404`

**Comment by guiweber** [comment]
This is because of #235

**Comment by geek1011** [comment]
Let's close this for now, and use just-install/just-install#235.
