### ISSUE TITLE
Contribution policy update: document that we prefer to install applications for all users

### ISSUE THREAD

**Issue by lvillani** [just-install/registry#239]
We should explicitly document that, since just-install runs as Administrator, we prefer packages that install for all users on the system.

**Comment by mimi89999** [comment]
All Squirrel installers install only for the current user. Squirrel does not support machine wide installs.

**Comment by lvillani** [comment]
That's why it's a "should" and not a "must" :wink:

**Comment by pgaskin** [comment]
We should consider adding a policy to suffix all user installers with `-user` to make this clear.
