### ISSUE TITLE
error 3010 while installing vagrant

### ISSUE THREAD

**Issue by cyagon** [just-install/registry#30]
i recently done some testing while  i have added programs to the registry, and then i stumbled upon this:

![unbenannt](https://user-images.githubusercontent.com/32183089/30779502-331e07d4-a0f3-11e7-9510-9788fbe1644a.PNG)

vagrant itself installs correctly, but this error basically "crashes" just-install. when you want to execute - lets say - ``just-install vagrant winscp`` - it installs vagrant, then crashes and dont want to install ``winscp`` and other software after vagrant.

**Comment by geek1011** [comment]
Thanks for reporting this issue. I will work on it soon.

Related issue: just-install/just-install#246

**Comment by geek1011** [comment]
@cyagon Can you confirm if my fix here has fixed the issue: https://ci.appveyor.com/project/lvillani/just-install/build/305/artifacts .

**Comment by geek1011** [comment]
https://github.com/just-install/just-install/commit/a3129e1a5ed56220bccbc37e0b7f44c001eb7d07

**Comment by cyagon** [comment]
It works!

![unbenannt](https://user-images.githubusercontent.com/32183089/30785698-19da1c7c-a16b-11e7-96a5-a32fb45cfde6.PNG)

**Comment by geek1011** [comment]
Great!

**Comment by geek1011** [comment]
just-install/just-install#245
