### ISSUE TITLE
virtualbox-extpack exits error 1

### ISSUE THREAD

**Issue by cyagon** [just-install/registry#36]
i played a bit with virtualbox-extpack, and it fails the installation with just-install since it asks for accepting a license according to [this ticket here](https://www.virtualbox.org/ticket/16674).

![unbenannt](https://user-images.githubusercontent.com/32183089/30786429-a18d2f06-a175-11e7-994b-35914f84aed4.PNG)

![unbenannt1](https://user-images.githubusercontent.com/32183089/30786442-cad878e8-a175-11e7-9488-47382ec83b84.PNG)

the result is similar to #30 . Just-Install "crashes" and dont want to install other software after virtualbox-extpack.

**Comment by guiweber** [comment]
This is a known issue with the updater: https://github.com/just-install/just-install-updater/issues/19

Basically the virtual box extpack installer needs to have the right file name to install properly and the updater currently does not update the file name properly.
