### ISSUE TITLE
Multiple Install Types

### ISSUE THREAD

**Issue by AKil47** [just-install/registry#38]
I am currently trying to create a registry entry for Paint.NET. However, the installer is stored on a zip file. In order to make the installer silent, I need to pass the `/auto` parameter to the installer executable. This means that this is a custom installer as well as a zip installer. **How do I implement multiple types of install types for a program?**

**Comment by guiweber** [comment]
I don't think we can do that at the moment, but it's something we should look into. I think we should not consider compression as an installer type, but just as a general parameter of the entry. This way, any installer type could be unpacked. This could even be detected automatically through the file extension when possible. For exemple, if the type is "msi" but the downloaded file is "zip" then we could unzip it and run the msi inside without adding anything to the registry.

@lvillani @geek1011

**Comment by AKil47** [comment]
We should maybe create a separate `actions` parameter in the registry for any commands that need to be done prior to the installation. This could include a `7zip` extraction command. This would mean that we would need to ship `7zip`'s CLI with the program but I do not think that it would be a huge deal.

**Comment by timohaas** [comment]
another example would be: DirectX End-User Runtimes (June 2010) [link](https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe)

it's an exe files which extracts "/q" its files into a directory, from the new directory you must  launch "DXSETUP.exe /silent". So its a also 2 step process.

**Comment by tlm-2501** [comment]
This is fully possible right now -- see #130 for how to do this, the tl;dr is that you use both `arguments` *and* `container` options. Inside `arguments`, `{{.installer}}` will refer to the one specified in the container option, not the zip file itself.
You may also take a look at #128 for a more complex custom installation flow that downloads the zip archive and then does some more complicated tasks to it after extracting, which essentially addresses the "actions" suggestion as it is.
Personally, I am against adding extra complications such as "actions" to JI. It can already be done with what we have right now, and if you need something more complex than just running a few commands in order, you can write an installation script (e.g. a `.bat` script or a PowerShell one), put it up on GitHub, and point JI to that script as an installer in the `x86` field, and then do your magic in that.
