### ISSUE TITLE
which software do you want to see next in just-install?

### ISSUE THREAD

**Issue by cyagon** [just-install/registry#79]

**Comment by SusanYost** [comment]
[Veeam Agent for Windows](https://www.veeam.com/windows-cloud-server-backup-agent.html) ([https://download2.veeam.com/VeeamAgentWindows_2.1.0.423.zip](https://download2.veeam.com/VeeamAgentWindows_2.1.0.423.zip)) and [paint.NET](https://www.getpaint.net/) would be awesome.

**Comment by cyagon** [comment]
paint.NET currently doesnt work, because its gonna be distributed only in ZIP-Archives with an executable within it https://github.com/just-install/registry/issues/38 . im gonna look at the veeam-agent in the next days.

**Comment by cyagon** [comment]
Update:

Sadly, the veeam-agent is gonna be distributed in the same way as paint.NET (only in ZIP-Archives with an executable in it #38). 
Unfortunately, I had only now time to look at it. Im sorry for the inconvenience.

**Comment by eir87O** [comment]
I'd love to see:

- Brave (desktop-version, I think the current one is portable?)
- WinCDEmu
- .DOT Framework (not sure if these are added already)
- Geek Uninstaller

I'd try and contribute if I wasn't so lame at programming and such.

**Comment by cyagon** [comment]
Brave is already there :) 
`just-install brave`

Which version of the .NET Framework do you want to see?
WinCDEmu is currently deprecated and not needed in Windows10. Do you still want it?
Geek Uninstaller is distributed only portable.

**Comment by eir87O** [comment]
I guess the Brave issue was just on my end then, when I installed it using that same command, it didn't create any shortcut or icon, yet I could still see it using Everything and open it with the .exe.

.NET Framework 4.5 is fine IMO, and I didn't know about the WinCDEmu issue, I still use it because I'm still on Windows 7. I hate Windows 10.

I just remembered about another one, Launchy (discontinued) or Wox (the one I'm currently using).

**Comment by cyagon** [comment]
im gonna add .NET Framework 4.7.1, since this is the latest one: https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers

wox has 2 dependencies at once (everything and python3). can you install wox without them (since this could be problematic for people who just want to install it without fuss)

**Comment by eir87O** [comment]
I think that is okay, as long as if it works after doing `just-install everything` and `just-install python3` before installing Wox. I currently do not have a Windows system close to me right now, so I can't really test that. :(

**Comment by cyagon** [comment]
i recently added dotnet: https://github.com/just-install/registry/commit/33c1eab748d8e4811ed2f321eb292e2561c061d5

about wox: it seems like you can install wox without everything and python3, as long as dotnet 4.5.2 and later is installed. so it should be ok.

**Comment by cyagon** [comment]
now wox is also in the config: 849497986e7d8565734401a5e4b57e989df2ff92

:)

**Comment by eir87O** [comment]
Thank you so much, I've tested it now and it's working flawlessly.

**Comment by eir87O** [comment]
I got two new suggestions:

- Rufus
- youtube-dl

**Comment by cyagon** [comment]
rufus is distributed only portable.
i will look after youtube-dl.

**Comment by geek1011** [comment]
@cyagon just-install can create shims so the path does not need to be modified

**Comment by cyagon** [comment]
i tested the configuration of youtube-dl with shims included:

````
    "youtube-dl": {
      "installer": {
        "kind": "copy",
        "options": {
          "destination": "{{.PROGRAMFILES_X86}}\\youtube-dl\\youtube-dl.exe",
          "shims": [
            "{{.PROGRAMFILES_X86}}\\youtube-dl\\youtube-dl.exe"
          ]
        },
        "x86": "https://github.com/rg3/youtube-dl/releases/download/{{.version}}/youtube-dl.exe"
      },
      "version": "2018.03.14"
    }
````
sadly, the shims arent working (on windows 10).

just-install shows that the creation of the shims is sucessfull
![unbenannt](https://user-images.githubusercontent.com/32183089/37436438-440bedaa-27e8-11e8-8672-a1213fedb6d2.PNG)

but even after a restart youtube-dl doesnt get regionized:
![unbenannt](https://user-images.githubusercontent.com/32183089/37436502-7e391f70-27e8-11e8-85c6-ded22d855d59.PNG)

youtube-dl does get regionized properly only if i set the %PATH% variable manually:
![unbenannt](https://user-images.githubusercontent.com/32183089/37436593-e05ee284-27e8-11e8-9d15-c8547fcbbf7a.PNG)

![unbenannt](https://user-images.githubusercontent.com/32183089/37436748-cc48e4b0-27e9-11e8-97e5-437956422d71.PNG)

youtube-dl also needs [visualcpp-2010](https://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe). should i add that too?

**Comment by cyagon** [comment]
about paint.net: it would be possible with the [container-option](https://github.com/just-install/registry/blob/master/just-install.json#L198), which is also used for colemak.

it would look like this:

````
    "paintnet": {
      "installer": {
        "kind": "custom",
        "options": {
          "container": {
            "installer": "paint.net.4.0.21.install.exe",
            "kind": "zip"
          },
          "arguments": [
            "{{.installer}}",
            "/auto"
          ]
        },
        "x86": "https://www.dotpdn.com/files/paint.net.{{.version}}.install.zip"
      },
      "version": "4.0.21"
    },
````

one problem is, that the name of the executable inside the .zip file changes every version step (same with the veeam-agent). in order to auto-update paint.net with the updater, it would need to look like this:

````
    "paintnet": {
      "installer": {
        "kind": "custom",
        "options": {
          "container": {
            "installer": "paint.net.{{.version}}.install.exe",
            "kind": "zip"
          },
          "arguments": [
            "{{.installer}}",
            "/auto"
          ]
        },
        "x86": "https://www.dotpdn.com/files/paint.net.{{.version}}.install.zip"
      },
      "version": "4.0.21"
    },
````

... which currently doesnt work:
![unbenannt](https://user-images.githubusercontent.com/32183089/37437402-4f63f152-27ed-11e8-8a2c-84a400449b3b.PNG)

**Comment by cyagon** [comment]
i thought of exeproxy setting the %PATH% variable directly, instead it essentially just creates hardlinks to one directory so you just need to create the %PATH% to this directory.

sometimes, i really need more sleep :sweat_smile:

**Comment by cyagon** [comment]
i thought exeproxy would set set the %PATH% variable directly, instead it essentially just creates hardlinks to one directory so you just need to create the %PATH% to this directory.

sometimes, i really need more sleep :sweat_smile:
i'm sorry for the inconvenience.

**Comment by cyagon** [comment]
i thought exeproxy would set set the %PATH% variable directly, instead it essentially just creates hardlinks to one directory so you just need to create the %PATH% to this directory.

sometimes, i really need more sleep 😅
i'm sorry for the inconvenience.

**Comment by cyagon** [comment]
i recently added youtube-dl: https://github.com/just-install/registry/commit/b37db138380db7bc49aaa06b9a6daceb654e3f60

**Comment by geek1011** [comment]
@cyagon Thanks for all your work! It's certainly not an inconvenience!

P.S. Speaking of the code for handling the registry, I might rewrite it to make it a bit more extensible, or at least write some documentation for it sometime soon.

**Comment by cyagon** [comment]
@geek1011 since youtube-dl would also need ffmpeg to fully work....

the ffmpeg builds are published in a folder in a zip file. this folder name changes every version step, a problem similar to paint.net.
in order to be able to deploy ffmpeg with just-install, just-install would need to be able to change folder names before the folder would be moved to {{.PROGRAMFILES}} .


````
    "ffmpeg": {
      "installer": {
        "kind": "zip",
        "options": {
````
> change folder name from `ffmpeg-3.4.2-win64-static` to `FFmpeg`
````
          "destination": "{{.PROGRAMFILES}}\\FFMpeg\\",
          "shims": [
            "{{.PROGRAMFILES}}\\FFmpeg\\bin\\ffmpeg.exe",
            "{{.PROGRAMFILES}}\\FFmpeg\\bin\\ffplay.exe",
            "{{.PROGRAMFILES}}\\FFmpeg\\bin\\ffprobe.exe"
          ]
        },
        "x86": "https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-{{.version}}-win32-static.zip",
        "x86_64": "https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-{{.version}}-win64-static.zip"
      },
      "version": "3.4.2"
    },
````

**Comment by geek1011** [comment]
Closing this for now, as it is getting kind of long and there hasn't been any recent activity.

**Comment by geek1011** [comment]
See #129 for ffmpeg.
