### ISSUE TITLE
mpc-hc got discontinued

### ISSUE THREAD

**Issue by cyagon** [just-install/registry#85]
https://mpc-hc.org/2017/07/16/1.7.13-released-and-farewell/

Should it be removed from the config?

**Comment by guiweber** [comment]
Maybe leave it there for a while and remove it when it's been more then a year?

**Comment by cyagon** [comment]
ok :)
i wanted to make sure if it is ok since mpc-hc is still pretty popular.

**Comment by geek1011** [comment]
I agree with guiweber. We should leave it until the link or compatibility breaks.

**Comment by geek1011** [comment]
Let's close this issue until the link stops working.
